apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # You can use a specific Nginx version if needed
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   # Use 'NodePort' or 'ClusterIP' if LoadBalancer is not available in your cluster
