apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mvc-app
  template:
    metadata:
      labels:
        app: spring-mvc-app
    spec:
      containers:
        - name: spring-mvc-app
          image: performancepoc.azurecr.io/spring-mvc:2.6
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "3Gi"    # Request 3 GB of memory
              cpu: "500m"      # Request 0.5 vCPU (500 milliCPU)
            limits:
              memory: "6Gi"    # Limit container to use up to 6 GB of memory
              cpu: "2"         # Limit container to use up to 2 vCPUs
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-app-service
  labels:
    app: spring-mvc-app-service
spec:
  selector:
    app: spring-mvc-app
  ports:
    - name: http
      port: 80
      targetPort: 8085
  type: LoadBalancer
